name: Packer CI Status Check

on:
  pull_request:
    paths:
      - '**.pkr.hcl'
      - '.github/workflows/packer-ci.yml'

jobs:
  packer_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.4" # Use the required packer version

      - name: Run packer fmt check
        run: packer fmt -check csye6225-aws-gcp.pkr.hcl

      - name: Run packer validate
        run: packer validate -var-file=".env.pkrvars.hcl" csye6225-aws-gcp.pkr.hcl
