name: Packer Image Build

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm test

    - name: Build application artifact
      run: zip -r webapp.zip . -x "*.git*" "node_modules/*" "*.env" "*.zip"

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup GCP CLI
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install Packer
      uses: hashicorp/setup-packer@v2

    - name: Format check
      run: packer fmt -check csye6225-aws-gcp.pkr.hcl

    - name: Validate template
      run: packer validate csye6225-aws-gcp.pkr.hcl

    - name: Build custom images
      run: |
        packer build -var "aws_region=${{ secrets.AWS_REGION }}" -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" csye6225-aws-gcp.pkr.hcl
